Added Backspace String Compare problem in DSA
Grow-with-Open-Source/DSA pull request #4
Opened 2023-10-26 07:22 UTC by rahulch-1

2023-10-26 07:37 UTC, iamwatchdogs commented
@rahulch-1 Please don't create another PR when you make your changes. You can commit your changes within the same PR, all you have to do is commit on the same branch that you're making the PR.

2023-10-29 07:41 UTC, iamwatchdogs commented
@rahulch-1 We have fixed your code for you to pass the linting checks.

2023-10-29 07:46 UTC, iamwatchdogs requested changes
Please make the requested changes.

2023-10-29 07:46 UTC, iamwatchdogs commented on Solved-Problems/Backspace_String_Compare/Main.java
> +import java.util.Stack;
@rahulch-1 Please provide the problem-related details within your program file as mentioned within the rules and guidelines in [CONTRIBUTING.md](../../blob/main/CONTRIBUTING.md#instructions-and-guidelines).

```suggestion
// Problem Name: <problem-name>
// Approach:     <data-structure> (or) <algorithm>
// Diffculty:    <mentioned-diffculty>
// Link:         <link-to-the-problem>

import java.util.Stack;
```

2023-10-29 16:33 UTC, iamwatchdogs requested changes
Please make these final changes, so that we can merge your pull request.

2023-10-29 16:33 UTC, iamwatchdogs commented on Solved-Problems/Backspace_String_Compare/Main.java
> +//Link: https://leetcode.com/problems/backspace-string-compare/
I believe it's a simple misunderstanding, there's no gap between the comments. Please remove those unnecessary new lines.

```suggestion
//Problem Name: 844.Backspace String Compare
//Approach: Using Stacks
//Difficulty: Easy
//Link: https://leetcode.com/problems/backspace-string-compare/
```

2023-10-29 16:58 UTC, rahulch-1 commented
Done the changes @iamwatchdogs

2023-10-29 18:07 UTC, iamwatchdogs approved these changes
The requested changes have been made. Review and Approved by @iamwatchdogs.

2023-10-29 18:10 UTC, merged

2023-10-29 18:12 UTC, iamwatchdogs commented
Thank you for contributing @rahulch-1, make sure to check your contributions on [GitHub Pages](https://grow-with-open-source.github.io/DSA/).